---
# tasks file for k8s-multinode-cluster-AWS
- name: "Installing docker, git, iproute-tc"
  package:
          name:  "{{ tool }}"
          state: present
  vars:
          tool:
                  - docker
                  - git
                  - iproute-tc
                 
- name: "coping daemon.json file"
  copy:
          src: daemon.json
          dest: /etc/docker/daemon.json

- name: "Starting Docker service"
  service:
          name: docker
          state: started
          enabled: yes

- name: "coping k8s repo"
  copy:
          src: kubernetes.repo
          dest: /etc/yum.repos.d/kubernetes.repo

- name: "Installng kubelet, kubectl & kubeadm"
  yum:
          name: "{{ packages }}"
          state: latest
          disable_excludes: all
          exclude: kubernetes
  vars:
          packages:
                  - kubelet
                  - kubeadm
                  - kubectl
                  
- name: "updating iptables for cni"
  sysctl:
          name: "{{ item }}"
          value: "1"
          sysctl_set: yes
          state: present
          reload: yes
  loop: 
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables

- name: "Starting kubelet service"
  service:
          name: kubelet
          state: started
          enabled: yes

- include_tasks: k8s-Master.yml
  when: inventory_hostname in groups['master']

- include_tasks: k8s-Worker.yml
  when: inventory_hostname in groups['worker']
